export const translations = {
  en: {
    dashboard: "Dashboard",
    cashierOrders: "Cashier / Orders",
    menuEdit: "Menu Edit",
    salesHistory: "Sales History",
    staffManagement: "Staff Management",
    quickActions: "Quick Actions",
    pendingBills: "Pending Bills",
    addNewDish: "Add New Dish",
    todayReport: "Today Report",
    logout: "Logout",
    todayRevenue: "Today Revenue",
    totalRevenue: "Total Revenue",
    orders: "Orders",
    activeTables: "Active Tables",
    topItems: "Top Items",
    recentOrders: "Recent Orders",
    refresh: "Refresh",
    clear: "Clear",
    from: "From",
    to: "To",
    pdf: "PDF",
    excel: "Excel",
    staffMembers: "Staff Members",
    saveStaff: "Save Staff",
    cancel: "Cancel",
    password: "Password",
    staffName: "Staff Name",
    addNewStaff: "Add New Staff",
    admin: "Admin",
    cashier: "Cashier",
    waiter: "Waiter",
    chef: "Chef",
    orderID: "Order ID",
    role: "Role",
    table: "Table",
    total: "Total",
    status: "Status",
    date: "Date",
    dishName: "Dish Name",
    price: "Price",
    saveDish: "Save Dish",
    searchDishes: "Search dishes...",
    all: "All",
    breakfast: "Breakfast",
    drinks: "Drinks",
    lunch: "Lunch",
    viewOrder: "View Order",
    kitchenDashboard: "Kitchen Dashboard",
    pendingOrders: "Pending Orders",
    connected: "Connected",
    disconnected: "Disconnected",
    activeOrders: "Active Orders",
    completed: "Completed",
    startCooking: "Start Cooking",
    cancelOrder: "Cancel Order",
    finish: "Finish",
    newOrder: "New Order",
    tableText: "Table",
    eat: "Eat",
    takeaway: "Takeaway",
    delivery: "Delivery",
    statusUpdateFailed: "Failed to update status.",
    waiting: "Waiting",
    seconds: "s",
    minutes: "m"
  },
  mm: {
    dashboard: "ဒက်ရှ်ဘုတ်",
    cashierOrders: "ငွေရှင်း / အော်ဒါ",
    menuEdit: "မီနူးပြင်ခြင်း",
    salesHistory: "အရောင်းမှတ်တမ်း",
    staffManagement: "ဝန်ထမ်းစီမံခန့်ခွဲမှု",
    quickActions: "အမြန်လုပ်ဆောင်ချက်များ",
    pendingBills: "ကျန်ငွေရှင်းရန်များ",
    addNewDish: "ဟင်းအသစ်ထည့်ရန်",
    todayReport: "ယနေ့အစီရင်ခံစာ",
    logout: "ထွက်မည်",
    todayRevenue: "ယနေ့ဝင်ငွေ",
    totalRevenue: "စုစုပေါင်းဝင်ငွေ",
    orders: "အော်ဒါများ",
    activeTables: "အသုံးပြုနေသောစားပွဲများ",
    topItems: "အရောင်းအများဆုံးများ",
    recentOrders: "နောက်ဆုံးအော်ဒါများ",
    refresh: "ပြန်တင်ရန်",
    clear: "ရှင်းရန်",
    from: "မှ",
    to: "အထိ",
    pdf: "PDF",
    excel: "Excel",
    staffMembers: "ဝန်ထမ်းများ",
    saveStaff: "ဝန်ထမ်းသိမ်းမည်",
    cancel: "မလုပ်တော့",
    password: "စကားဝှက်",
    role: "ရာထူး",
    staffName: "ဝန်ထမ်းအမည်",
    addNewStaff: "ဝန်ထမ်းအသစ်ထည့်မည်",
    admin: "အက်ဒမင်",
    cashier: "‌‌ငွေကိုင်",
    waiter: "စားပွဲထိုး",
    chef: "စားဖိုမှုး",
    orderID: "မှာယူမှု ID",
    table: "စားပွဲ",
    total: "စုစုပေါင်း",
    status: "အခြေအနေ",
    date: "နေ့စွဲ",
    dishName: "ဟင်းအမည်",
    price: "စျေးနှုန်း",
    saveDish: "သိမ်းမည်",
    restaurantMenu: "စားသောက်ဆိုင် မီနူး",
    searchDishes: "ဟင်းလျာရှာရန်...",
    all: "အားလုံး",
    breakfast: "မနက်စာ",
    drinks: "အချိုရည်",
    lunch: "နေ့လယ်စာ",
    viewOrder: "အော်ဒါကြည့်မည်",
    kitchenDashboard: "မီးဖိုချောင် ဒက်ရှ်ဘုတ်",
    pendingOrders: "စောင့်နေသော အော်ဒါများ",
    connected: "ချိတ်ဆက်ထားသည်",
    disconnected: "ချိတ်ဆက်မှုမရှိပါ",
    activeOrders: "လုပ်ဆောင်နေသော အော်ဒါများ",
    completed: "ပြီးဆုံးသော အော်ဒါများ",
    startCooking: "စတင်ချက်မည်",
    cancelOrder: "အော်ဒါဖျက်မည်",
    finish: "ပြီးပြီ",
    newOrder: "အော်ဒါအသစ်",
    tableText: "စားပွဲ",
    eat: "ဆိုင်တွင်စား",
    takeaway: "ပါဆယ်",
    delivery: "ပို့ဆောင်",
    statusUpdateFailed: "အခြေအနေပြောင်းလို့ မရပါ။",
    waiting: "စောင့်ချိန်",
    seconds: "စက္ကန့်",
    minutes: "မိနစ်",

  }
};