export const translations = {
  en: {
    dashboard: "Dashboard",
    cashierOrders: "Cashier / Orders",
    menuEdit: "Menu Edit",
    salesHistory: "Sales History",
    staffManagement: "Staff Management",
    quickActions: "Quick Actions",
    pendingBills: "Pending Bills",
    addNewDish: "Add New Dish",
    todayReport: "Today Report",
    logout: "Logout",
    todayRevenue: "Today Revenue",
    totalRevenue: "Total Revenue",
    orders: "Orders",
    activeTables: "Active Tables",
    topItems: "Top Items",
    recentOrders: "Recent Orders",
    refresh: "Refresh",
    clear: "Clear",
    from: "From",
    to: "To",
    pdf: "PDF",
    excel: "Excel",
    staffMembers: "Staff Members",
    saveStaff: "Save Staff",
    cancel: "Cancel",
    password: "Password",
    staffName: "Staff Name",
    addNewStaff: "Add New Staff",
    admin: "Admin",
    cashier: "Cashier",
    waiter: "Waiter",
    chef: "Chef",
    orderID: "Order ID",
    role: "Role",
    table: "Table",
    total: "Total",
    status: "Status",
    date: "Date",
    dishName: "Dish Name",
    price: "Price",
    saveDish: "Save Dish"
  },
  mm: {
    dashboard: "ဒက်ရှ်ဘုတ်",
    cashierOrders: "ငွေရှင်း / အော်ဒါ",
    menuEdit: "မီနူးပြင်ခြင်း",
    salesHistory: "အရောင်းမှတ်တမ်း",
    staffManagement: "ဝန်ထမ်းစီမံခန့်ခွဲမှု",
    quickActions: "အမြန်လုပ်ဆောင်ချက်များ",
    pendingBills: "ကျန်ငွေရှင်းရန်များ",
    addNewDish: "ဟင်းအသစ်ထည့်ရန်",
    todayReport: "ယနေ့အစီရင်ခံစာ",
    logout: "ထွက်မည်",
    todayRevenue: "ယနေ့ဝင်ငွေ",
    totalRevenue: "စုစုပေါင်းဝင်ငွေ",
    orders: "အော်ဒါများ",
    activeTables: "အသုံးပြုနေသောစားပွဲများ",
    topItems: "အရောင်းအများဆုံးများ",
    recentOrders: "နောက်ဆုံးအော်ဒါများ",
    refresh: "ပြန်တင်ရန်",
    clear: "ရှင်းရန်",
    from: "မှ",
    to: "အထိ",
    pdf: "PDF",
    excel: "Excel",
    staffMembers: "ဝန်ထမ်းများ",
    saveStaff: "ဝန်ထမ်းသိမ်းမည်",
    cancel: "မလုပ်တော့",
    password: "စကားဝှက်",
    role: "ရာထူး",
    staffName: "ဝန်ထမ်းအမည်",
    addNewStaff: "ဝန်ထမ်းအသစ်ထည့်မည်",
    admin: "အက်ဒမင်",
    cashier: "‌‌ငွေကိုင်",
    waiter: "စားပွဲထိုး",
    chef: "စားဖိုမှုး",
    orderID: "မှာယူမှု ID",
    table: "စားပွဲ",
    total: "စုစုပေါင်း",
    status: "အခြေအနေ",
    date: "နေ့စွဲ",
    dishName: "ဟင်းအမည်",
    price: "စျေးနှုန်း",
    saveDish: "သိမ်းမည်"

  }
};